# Generated by Django 6.0 on 2026-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='passenger_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='passenger_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='passenger_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='passenger_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
