# Generated by Django 6.0 on 2026-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0002_busbooking_passenger_age_busbooking_passenger_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='bus_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='busmodel',
            unique_together={('bus_number', 'source', 'destination', 'travel_date', 'departure_time')},
        ),
    ]
