# Generated by Django 6.0 on 2026-02-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_alter_busmodel_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
