# Generated by Django 6.0 on 2026-02-16 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_app', '0003_alter_busmodel_bus_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airline_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('travel_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flight_app.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destination', to='bus_app.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_source', to='bus_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST_CLASS', 'First Class')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baggage_check_in', models.CharField(default='15 KG', max_length=50)),
                ('baggage_cabin', models.CharField(default='7 KG', max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='flight_app.flightmodel')),
            ],
            options={
                'unique_together': {('flight', 'class_type')},
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.PositiveIntegerField()),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('booking_status', models.CharField(default='CONFIRMED', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flightclass')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flightmodel')),
            ],
        ),
    ]
