# Generated by Django 6.0 on 2026-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_flightbooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='passenger_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
