# Generated by Django 6.0 on 2026-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_flightbooking_passenger_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='seat_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='flightclass',
            name='class_type',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST_CLASS', 'First Class')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
