# Generated by Django 6.0 on 2026-02-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbooking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
