# Generated by Django 6.0 on 2026-02-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0002_trainbooking_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainbooking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='trainbooking',
            unique_together={('coach', 'seat_number')},
        ),
    ]
