# Generated by Django 6.0 on 2026-02-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0003_trainbooking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
