# Generated by Django 6.0 on 2026-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0004_alter_trainbooking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodel',
            name='train_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
