# Generated by Django 6.0 on 2026-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0005_alter_trainmodel_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainbooking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainbooking',
            name='seat_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='traincoach',
            name='coach_type',
            field=models.CharField(choices=[('1AC', 'First Class AC'), ('2AC', 'Second Class AC'), ('3AC', 'Third Class AC'), ('SL', 'Sleeper'), ('2S', 'Second Sitting')], max_length=30),
        ),
    ]
